server:
  port: 8181
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名
      routes: #配置路由规则
        - id: oauth2_route
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: provider_route
          uri: http://localhost:8201
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
        - id: order_route
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: pay_route
          uri: lb://pay
          predicates:
            - Path=/pay/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8282/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"