server:
  port: 8282
spring:
  application:
    name: auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"